export const debug = import.meta.env.DEV
export const sansExcludeSelector = [
  '.monaco-editor *',
  'v-text',
  '[data-virgo-text=true]',
  // math
  'mjx-container *',
  // icons
  '[class*=material-symbols]',
  '[class*=codicon]',
  '[class*=icon]',
  '[class*=icon] *',
  '[class*=Icon]',
  '[class*=Icon] *',
  '[class*="terminal"] *',
  '[class^="fui-"]',
  '[class*="fui-"]',
  '[class*="fa"]',
  '[class*=heroButton]',
  '.pi, .pi *',
  // elements
  'em, i, svg *, kbd, kdb *, samp, samp *, var, var *, tt',
]
export const monospaceSelectors = [
  '.monaco-editor *',
  'html body pre',
  'pre *',
  'pre.CodeMirror-line *',
  'code',
  'code *',
  '.code',
  '.code *',
  '.mono',
  '.text-mono',
  '.text-mono *',
  'pre .token',
  'pre code *',
  'pre section *',
  'body pre code.hljs',
  '.prettyprint *',
  '.hljs',
  '.hljs *',
  '[class*=hljs]:not(.hljs-engine) *',
  'code[class*="language-"] *',
  'pre[class*="language-"] *',
  'body .prism .token',
  '.cm-editor *',
  '.font-mono',
  '[font-mono]',
  '.font-mono>*',
  '[font-mono]>*',
  '.monaco-mouse-cursor-text',
  '#vscode-editor *',
  '.enlighter *',
  '.syntaxhighlighter :is(code, .line)',
  'table.highlight *',
  'pre[data-lang] code',
  '.Typist',
  '.Typist *',
  '.ace_editor *',
  '[data-rnw-int-class*="codeblock"] *',
  '.codecolorer-container *',
  '.codeblock *',
  '.swagger-ui :is(.code, code)',
  '.dp-highlighter *',
  '.prism-code *',
  '.CodeMirror-code *',
  '.code-editor :is(.token-line, .token)',
  '[class*="monospace"]',
  '[class*="monospace"] *',
  '[class*="terminal"] *',
  '.whitespace-pre',
  '[class^=console]>*',
  'samp',
  'code-container *',
  'span:has(>.r-crgep1[data-highlighting]) *',
  'kbd',
  'tt',
  '[class^=code-block]',
]
export const blocklist = [
  'font',
  'ziti',
  'izihun',
  'foundertype',
  'hanyi',
  'adobe',
  'localhost',
  'mono',
  'latex',
  'typeof',
  'jetbrains',
  'unicode',
  'math',
  'twitter',
  'openvim',
]
